CREATE TEMPORARY TABLESPACE ARGUS_TEMP TEMPFILE 
  '/db/targusKTP/ARGUS_TEMP01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE TABLESPACE ARGUS_SYNC_IND DATAFILE 
  '/db/targusKTP/ARGUS_SYNC_IND01.DBF' SIZE 300M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_SYNC_DATA DATAFILE 
  '/db/targusKTP/ARGUS_SYNC_DATA01.DBF' SIZE 300M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_NUMBERS_IND DATAFILE 
  '/db/targusKTP/ARGUS_NUMBERS_IND01.DBF' SIZE 200M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_NUMBERS DATAFILE 
  '/db/targusKTP/ARGUS_NUMBERS01.DBF' SIZE 200M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_LOGS DATAFILE 
  '/db/targusKTP/ARGUS_LOGS01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_IND DATAFILE 
  '/db/targusKTP/ARGUS_IND01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_DIRECTORY_IND DATAFILE 
  '/db/targusKTP/ARGUS_DIRECTORY_IND01.DBF' SIZE 256M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_DIRECTORY DATAFILE 
  '/db/targusKTP/ARGUS_DIRECTORY01.DBF' SIZE 300M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_CP_LINK_IND DATAFILE 
  '/db/targusKTP/ARGUS_CP_LINK_IND01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_CP_LINK DATAFILE 
  '/db/targusKTP/ARGUS_CP_LINK01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_CP_IND DATAFILE 
  '/db/targusKTP/ARGUS_CP_IND02.DBF' SIZE 512M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS_CP DATAFILE 
  '/db/targusKTP/ARGUS_CP01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ARGUS DATAFILE 
  '/db/targusKTP/ARGUS01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO;

