DROP PUBLIC DATABASE LINK SIPARCH;

CREATE PUBLIC DATABASE LINK SIPARCH
 CONNECT TO SIP_KZ
 IDENTIFIED BY <PWD>
 USING '(DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = sip-tst2.mrk.vt.ru)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = SIPARCH)
    )
  )';
