--SELECT version FROM v$timezone_file;
CREATE TABLESPACE INTGR_CRM_STARTIP_DATA DATAFILE 
'+SIPCH_DATA/startip/datafile/integr.01' SIZE 5000M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.01' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.02' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.03' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.04' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.05' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.06' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.07' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.08' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.09' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.10' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.11' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.12' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.13' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.14' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.15' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.16' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.17' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.18' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.19' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.20' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.21' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.22' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.23' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.24' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.25' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.26' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.27' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.28' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.29' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.30' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.31' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.32' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.33' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.34' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.35' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.36' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.37' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.38' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.39' SIZE 32767M AUTOEXTEND OFF;
ALTER TABLESPACE USERS ADD DATAFILE '+SIPCH_DATA/startip/datafile/users.40' SIZE 32767M AUTOEXTEND OFF; 