--ALTER TABLE "SIP_W"."TB_WTMPS_SESSION_CHARGES" ADD CONSTRAINT "TWSC_TWSA_FK" FOREIGN KEY ("TWSC_TWSA_ID") REFERENCES "SIP_W"."TB_WTMPS_SESSIONS_ARCHIVE" ("TWSA_N") ENABLE NOVALIDATE;


select max(TWSC_TWSA_ID) from SIP_W.TB_WTMPS_SESSION_CHARGES partition (PART2015_03);
--1683548840
select max(TWSA_N) from SIP_W.TB_WTMPS_SESSIONS_ARCHIVE partition (PART2015_03);