--select * from dba_jobs_running;
select * from dba_users where username not in
('MGMT_VIEW','CTXSYS','XSYS','XDB','SYS','SYSTEM',
'DBSNMP','SYSMAN','ANONYMOUS','OUTLN','PERFSTAT',
'MDSYS','WMSYS','SI_INFORMTN_SCHEMA','ORDSYS','ORACLE_OCM',
'TSMSYS','DIP','ORDPLUGINS','OLAPSYS','SQLTXPLAIN','SQLTXADMIN',
'MDDATA','EXFSYS','DMSYS','LOGSTDBY_ADMINISTRATOR', 
'OEM_MONITOR', 'WKPROXY','WK_TEST', 'WKUSER','LBACSYS', 'DMSYS','WKSYS',
'OLAPDBA', 'OLAPSVR', 'OLAP_USER','ODM','QS','QS_ADM','QS_CB','QS_CBADM',
'APEX_PUBLIC_USER','APEX_030200','ORDDATA','ANONYMOUS','CTXSYS','DBSNMP','QS_CS','QS_ES','QS_OS','QS_WS','SPOTLIGHT','HR','SCOTT','SH','OE','XS$NULL','APPQOSSYS',
'EXFSYS','LBACSYS','MDSYS','MGMT_VIEW','OLAPSYS','ORDDATA','OWBSYS','ORDPLUGINS','ORDSYS','OUTLN','SI_INFORMTN_SCHEMA','SYS','SYSMAN','SYSTEM','WK_TEST','WKSYS','WKPROXY','WMSYS','XDB',
'DIP','FLOWS_040100','FLOWS_FILES','MDDATA','ORACLE_OCM','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL','BI','HR','OE','PM','IX','SH');