CREATE USER DEBTORS IDENTIFIED BY uBj8O765j
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
GRANT CONNECT TO DEBTORS WITH ADMIN OPTION;
GRANT RESOURCE TO DEBTORS WITH ADMIN OPTION;
ALTER USER DEBTORS DEFAULT ROLE ALL;
GRANT CREATE ANY JOB TO DEBTORS;
GRANT CREATE ANY SYNONYM TO DEBTORS;
GRANT CREATE JOB TO DEBTORS;
GRANT CREATE PUBLIC SYNONYM TO DEBTORS;
GRANT CREATE SYNONYM TO DEBTORS;
GRANT CREATE VIEW TO DEBTORS;
GRANT MANAGE SCHEDULER TO DEBTORS;
GRANT SELECT ANY DICTIONARY TO DEBTORS;
GRANT SELECT ANY TABLE TO DEBTORS;
GRANT UNLIMITED TABLESPACE TO DEBTORS WITH ADMIN OPTION;
GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO DEBTORS;
GRANT SELECT ON SYS.V_$SESSION TO DEBTORS;
GRANT SELECT ON SYS.V_$SQLTEXT TO DEBTORS;