ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2042_08
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2042_09
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2042_10
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2042_11
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2042_12
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_01
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_02
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_03
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_04
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_05
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_06
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_07
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_08
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_09
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_10
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_11
  UPDATE GLOBAL INDEXES
/

ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE
  DROP PARTITION PART2043_12
  UPDATE GLOBAL INDEXES
  PARALLEL 2
/