/*
---------------SIP_W.ABONENT_JN------------------------------------------------
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.ABONENT_JN split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
--ALTER TABLE SIP_W.ABONENT_JN MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
-------------------END OF SIP_W.ABONENT_JN----------------------------------------
*/


/*
---------------SIP_W.CT_POOLS_JN------------------------------------------------
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.CT_POOLS_JN split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
--ALTER TABLE SIP_W.CT_POOLS_JN MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
-------------------END OF SIP_W.CT_POOLS_JN----------------------------------------
*/


/*
---------------SIP_W.TB_ACCOUNTS_JN------------------------------------------------
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
--ALTER TABLE SIP_W.TB_ACCOUNTS_JN MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
-------------------END OF SIP_W.TB_ACCOUNTS_JN----------------------------------------
*/

--ALTER TABLE SIP_W.TB_ACCOUNTS_JN MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;

-----Пришлось сделать ребилд индексов для таблицы SIP_W.TB_ACCOUNTS_JN, тк как поместил он их в tablespace USERS а не в INDX-------------
/*
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_AB_ID_IX  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.JACC_DATETIME_IX  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
*/



/* -----------Сравнение с явным указанием тейблспейсов------------------
alter table SIP_W.TB_ACCOUNTS_JN split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;

alter table sip_w.IBS_ABS_LOG split partition PART_MAXVALUE at 
(TO_DATE('022013','mmyyyy'))  into 
(partition PART2013_01 TABLESPACE USERS, partition PART_MAXVALUE TABLESPACE USERS);
*/



/*
---------------SIP_W.TB_BLOCKING_ARCHIVE------------------------------------------------
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_BLOCKING_ARCHIVE split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;

*/
/*
--индексы партицированные
BL_ARC_AB_FK_I
BL_ARC_BC_FK_I
BL_ARC_CPU_FK_I

BL_ARC_US_FK_I
BL_ARC_USS_FK_I
BL_ARC_USS_FK_I
BL_TO_I
*/

--ALTER TABLE SIP_W.TB_BLOCKING_ARCHIVE MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
/*

ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_AB_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;


ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_BC_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_CPU_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_US_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_ARC_USS_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;


ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.BL_TO_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

-------------------END OF SIP_W.TB_BLOCKING_ARCHIVE----------------------------------------
*/


/*
TB_INVOICES
--индекы
INV_AB_DATE
INV_AB_DATE
INV_AB_FK_I
INV_IST_FK_I
INV_ITP_FK_I

INV_SRD_FK_I
INV_SRD_FK_I
INV_US_FK_I
*/

/*
------------------------TB_INVOICES-----------------------------------

alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_INVOICES split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;

ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_AB_DATE  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_IST_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_ITP_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_SRD_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.INV_US_FK_I  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

------------------------END TB_INVOICES-----------------------------------
*/


---------------SIP_W.TB_LDAP_TASKS-------------------------------------
/*
alter table SIP_W.TB_LDAP_TASKS split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_LDAP_TASKS split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_LDAP_TASKS split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
*/
--with saubpart скрипт не отрработал. индексы в USERS
/*
ALTER INDEX SIP_W.LDT_AB_IDR  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_AB_IDR  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_AB_IDR  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_AB_IDR  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_AB_IDR  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
*/
/*
ALTER INDEX SIP_W.LDT_BL_IDR  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_BL_IDR  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_BL_IDR  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_BL_IDR  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_BL_IDR  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
*/
/*
ALTER INDEX SIP_W.LDT_IDXR  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_IDXR  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_IDXR  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_IDXR  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_IDXR  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.LDT_USERR  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_USERR  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_USERR  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_USERR  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.LDT_USERR  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;

ALTER INDEX SIP_W.REALM_MULTIF_IR  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.REALM_MULTIF_IR  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.REALM_MULTIF_IR  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.REALM_MULTIF_IR  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.REALM_MULTIF_IR  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
*/
--индк
/*
LDT_AB_IDR
LDT_BL_IDR
LDT_IDXR
LDT_USERR
REALM_MULTIF_IR
*/

-----------------------------------END SIP_W.TB_LDAP_TASKS-------------------------------------


/*
---------------------------TB_OPTION_STATUS_JN--------------------------------------

alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.TB_OPTION_STATUS_JN split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
--ALTER TABLE SIP_W.TB_OPTION_STATUS_JN MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
*/
/*
--Не надо. был в users----
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
ALTER INDEX SIP_W.OPSJ_USER_IDX  REBUILD PARTITION PART_MAXVALUE  TABLESPACE INDX;
------
*/


--OPSJ_USER_IDX
---------------------------END TB_OPTION_STATUS_JN--------------------------------------


----------------TB_SERVICES-------------
--уже был расширен


----------------TB_SERVICES_JN
--уже был расширен


----------------TB_USER_SERV_ATTRS_JN
--уже был расширен


--------------------TB_WTMPS_ARCHIVE
--уже был расширен


--------------TB_WTMPS_SESSION_CHARGES
--уже был расширен
-------------------TB_WTMPS_SESSIONS_ARCHIVE
--уже был расширен




----------------------SIP_W.VOIP_LOG_DETAIL-----------------------
/*
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_W.VOIP_LOG_DETAIL split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
--ALTER TABLE SIP_W.VOIP_LOG_DETAIL MODIFY PARTITION PART2014_02 REBUILD UNUSABLE LOCAL INDEXES;
*/


/*
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_02  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_03  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_04  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_05  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_06  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_07  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_08  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_09  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_10  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_11  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2014_12  TABLESPACE INDX;
ALTER INDEX SIP_W.LGD_LOG_FK_I  REBUILD PARTITION PART2015_01  TABLESPACE INDX;
*/



----------------------SIP_IBS.ABS_EXP_SERVICES---------------------
/*
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('032014','mmyyyy')) into 
(partition PART2014_02, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('042014','mmyyyy')) into 
(partition PART2014_03, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('052014','mmyyyy')) into 
(partition PART2014_04, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('062014','mmyyyy')) into 
(partition PART2014_05, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('072014','mmyyyy')) into 
(partition PART2014_06, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('082014','mmyyyy')) into 
(partition PART2014_07, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('092014','mmyyyy')) into 
(partition PART2014_08, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('102014','mmyyyy')) into 
(partition PART2014_09, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('112014','mmyyyy')) into 
(partition PART2014_10, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('122014','mmyyyy')) into 
(partition PART2014_11, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('012015','mmyyyy')) into 
(partition PART2014_12, partition PART_MAXVALUE) update global indexes;
alter table SIP_IBS.ABS_EXP_SERVICES split partition PART_MAXVALUE at
(TO_DATE('022015','mmyyyy')) into 
(partition PART2015_01, partition PART_MAXVALUE) update global indexes;
*/