    
    
--    EXECUTE DBMS_LOGMNR.ADD_LOGFILE(LOGFILENAME => '+SIPCH_REDO/startip/redo05.log', OPTIONS => DBMS_LOGMNR.NEW);
   -- EXECUTE DBMS_LOGMNR.START_LOGMNR(OPTIONS => DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG);
    
    --SELECT * FROM v$logmnr_contents where rownum <10;
    
    --EXECUTE DBMS_LOGMNR.END_LOGMNR();