ALTER DATABASE SET TIME_ZONE='Europe/Samara';
--shutdown immediate;
--startup;

SELECT SESSIONTIMEZONE, DBTIMEZONE, SYSTIMESTAMP, TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS')  FROM DUAL;

SELECT UNIQUE TZNAME FROM V$TIMEZONE_NAMES;

select * from DATABASE_PROPERTIES;