// Copyright (c) 2016 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(k){var d,b={_breaker:{},_start:null,each:function(){var a;return function(c,e,f){var h,d;d=b.type(c);var l=new Date;if(1===arguments.length)a=arguments[0];else if(f=b.extend({timeout:!1},f),"object"===d&&c.hasOwnProperty)for(h in c){if(c.hasOwnProperty(h)&&(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(l)>a))break}else if(c){h=0;for(d=c.length;h<d&&!(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(l)>a);h++);}}}(),extend:function(a){var c,e,b,h,d=arguments.length;a=a||{};for(e=1;e<d;e++)if(h=
arguments[e],void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(c,a){try{return("function"===typeof window[a]||"object"===typeof window[a])&&c instanceof window[a]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||
"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var e="array"===b.type(a)?[]:{};b.each(a,function(a,h){c(a,h)&&("array"===b.type(e)?e.push(a):e[h]=a)});return e},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,b){return(c=a[c])&&c.split?c.split(b||" "):[]},batchable:function(a,
c){c=c||b.noop;var e=function(){return b.extend({batch:!0,timeout:100},c())},f=b.traits.cors&&b.traits.json,h=[],d=null,l=function(){null!==d&&(clearTimeout(d),d=null);1===h.length?a.apply(null,h[0].arguments):1<h.length&&a.apply(null,h);h=[]},g=function(){h.push({arguments:b.toArray(arguments),batch:!0});!f||!e().batch?l():null===d&&(d=setTimeout(b.entryPoint(b.bind(function(){l()},this)),e().timeout))};b.extend(g,{flush:l,now:a});return g},batchArgs:function(a,c){return b.map(a,function(a){return void 0===
c?a.arguments:a.arguments[c]})},batchCallType:function(a){var c;return b.reduce(null,a,function(a,b){c=b[0];return null!==a&&c!==a?"batch":c})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(c){return"object"===b.type(c)&&c.batch&&"array"===b.type(c.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(f,h,d){if(f){var l=f[c];if(l||void 0!==
d)return l||(l=++b),a[l]||(f[c]=l,a[l]={}),void 0!==d&&(a[l][h]=d),"string"===typeof h?a[l][h]:a[l]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},a)},commonParams:function(a,c){var e;c=c||{};e={drKey:c.key?null:c.dr_key,key:c.key,libId:c.library_id,subId:c.sub_id};("click"===a||"ping"===a)&&b.extend(e,{cuid:c.cuid,
loc:location.href,v:1},e);return e},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===c)return!0;return!1},cors:function(a,c,e){var f;f=new window.XMLHttpRequest;f.onreadystatechange=function(){if(4===f.readyState&&200===f.status){var c=
b.noop,a=[],h;if(e)e(f.responseText);else if("string"===b.type(f.responseText)&&(h=f.responseText.match(/^\s*(?:\/\*\*\/)?([^(\s]+)\s*\((.*)\);?\s*$/)))c=h[1].replace(/(^\s+|\s+$)/g,""),a=b.fromJSON("["+h[2]+"]"),window[c].apply(window,a)}};try{return f.open("POST",a),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.withCredentials=!0,f.send(c),!0}catch(h){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,e,f){var h;a=(f||document).createElement(a);
c=c||{};e=e||{};for(h in c)void 0!==c[h]&&(a[h]=c[h]);b.css(a,e);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(f){}return a},destructing:function(a){return function(c){var a=!1,b;return function(){a||(b=c.apply(null,arguments),a=!0);return b}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},
escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(f){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},every:function(a,c){return Boolean(!b.some(a,function(a){return!c(a)}))},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,f){if(void 0!==f)a=f,c=b;else return function(){if(a)try{return b.apply(this,
arguments)}catch(f){c(f)}else return b.apply(this,arguments)}}}(),find:function(a,c,e){var f;b.each(a,function(a,e){if(c(a,e))return f=a,b._breaker},e);return f},generateNodeFilter:function(){var a=function(a,b){var h,d;b=","+b.join(",")+",";h=0;for(d=a.length;h<d;h++)if(c(a[h],b))return!0;return!1},c=function(c,a){return-1!==a.indexOf(","+c+",")};return function(e){e=b.extend({custom:null,classes:[],rels:[],tags:[]},e);e.tags.length&&(e.tags=","+e.tags.join(",").toLowerCase()+",");return function(f,
h){h=b.extend({ancestors:!0,self:!0},h);var d=function(f,h){var d;if(d=!(e.tags.length&&c(f.nodeName.toLowerCase(),e.tags))){if(d=e.classes.length){d=e.classes;var g=b.attrValues(f,"className");d=a(d,g)}if(d=!d){if(d=e.rels.length)d=e.rels,g=b.attrValues(f,"rel"),d=c(f.nodeName.toLowerCase(),",a,")&&a(d,g);d=!d&&!("function"===b.type(e.custom)&&e.custom(f,h))}}return d};if(h.self&&!d(f,!0))return!1;if(h.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!d(f,!1))return!1;return!0}}}(),
fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,e=Infinity,f=Infinity,h=-Infinity,d=-Infinity,l;for(a=0;a<c;a++)l=b.position(arguments[a]),e=Math.min(e,l.x),f=Math.min(f,l.y),h=Math.max(h,l.x+arguments[a].offsetWidth),d=Math.max(d,l.y+arguments[a].offsetHeight);
return{x:e,y:f,w:h-e,h:d-f,x1:e,y1:f,x2:h,y2:d}},getActualHref:function(a){return b.cache(a,"href")||a.href},hasAttrValue:function(a,c,e,f){return c?b.contains(b.attrValues(a,c,f),e):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&
a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},links:function(){var a=["http:","https:"],c=function(c,f){return b.all(c,function(c){return c.href&&(!f.filter_by_scheme||b.contains(a,c.protocol))&&(!f.filter_homepages||"/"!==c.pathname)&&(!f.filter_internal||c.hostname!==b.context(c).location.hostname)})};return function(a,f,h){h=b.extend({filter_homepages:!0,filter_internal:!0,
filter_by_scheme:!0},h);f=b.map(f.split(","),function(c){return c+" a[href]"}).join(",");return c(b.withScope(a,f,{ancestors:!1,consolidate:!0}),h)}}(),map:function(a,c,e){return b.reduce([],a,function(a,b,e){a.push(c(b,e));return a},e)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(e){return!0}},mergeable:function(a){var c=function(){return b.extend({batchFn:b.noop,nonBatchFn:b.noop,batchable:!0,timeout:100},a())};return b.batchable(function(){b.batched(arguments)?
c().batchable?b.each(b.batchArgs(arguments),function(a){c().batchFn.apply(this,a)}):c().nonBatchFn.apply(this,arguments):c().nonBatchFn.apply(this,arguments)},function(){return{batch:!0,timeout:c().timeout}})},mergeParams:function(a){var c,e,f,h=arguments.length,d=function(e,f){c=a[f];a.hasOwnProperty(f)&&b.isArray(e)&&b.isArray(c)?a[f]=b.unique(c.concat(e)):a[f]=e};for(e=1;e<h;e++)f=arguments[e],b.each(f,d);return b.prune(a)},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,
function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,e,f){var h,d,l;if(1===arguments.length)a=c;else{if(2===arguments.length){if(!a)return;f=e;e=c;c=a}else h=b.toArray(arguments).slice(3,arguments.length);try{d=c["on"+e]}catch(g){}"function"===typeof d&&(c["on"+e]=b.bind(function(a){a=a||window.event;var e=d.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==e&&!1!==a.returnValue&&(a.returnValue=e),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&
a.preventDefault(),a.returnValue):e})()},this));l=b.entryPoint(function(){if(a.enabled())return f.apply(null,b.toArray(arguments).concat(h||[]))});c.addEventListener?c.addEventListener(e,l,!1):c.attachEvent&&c.attachEvent("on"+e,l)}}}(),packageArgs:function(){return b.toArray(arguments)},position:function(a,c){var e,f=0,h=0,d=0,l=0;c=c||document;if(!b.isInDom(a))return!1;e=a;do f+=e.offsetLeft,h+=e.offsetTop,e=e.offsetParent;while(e);e=a;do d+=e.scrollLeft,l+=e.scrollTop,e=e.parentNode;while(e&&e!==
c.body);return{x:f-d,y:h-l}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});return a},ready:function(){var a=!1,c=[],e=!1,f,h,d,l,g;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",d,!1);g()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),g())});f=function(){if(!a){a=!0;if("interactive"===
document.readyState||"complete"===document.readyState)return g();if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",l);var c=!1;try{c=null===window.frameElement}catch(e){}document.documentElement.doScroll&&c&&h()}b.on(window,"load",g)}};h=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(h),1);return}g()}};g=function(){if(!e){if(!document.body)return setTimeout(b.entryPoint(g),
13);e=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){f();e?a():c.push(a)}}(),reduce:function(a,c,e,f){b.each(c,function(c,b){a=e(a,c,b)},f);return a},reformatKeys:function(a){var c,e,f=function(a){return"_"+a.toLowerCase()};for(c in a)e=c.replace(/([A-Z])/g,f),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),e!==c&&(a[e]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var e,f,h=b.attrValues(a,"className");e=0;for(f=h.length;e<f;e++)h[e]===c&&delete h[e];
a.className=h.join(" ")}},request:function(a,c,e){var f,h,d,l=b.uniqid("vglnk_"),g=b.toArray(arguments).slice(3,arguments.length),r=function(a,c,e){var f={},d=!!c.length,h=!0===e||!1===e;if(d||h)a=b.createA(a),d&&(f.search="?"+c),h&&(c=a.protocol||b.context(a).location.protocol||"http:",f.protocol=c.replace(/s?:$/,function(){return e?"s:":":"})),a=b.extend(a,f).href;return a};h=function(a,c){var e={},f=b.commonParams();e[c]={};b.each(a,function(a,b){b in f?e[b]=a:e[c][b]=a});e[c]=b.toJSON(e[c]);return b.prune(e)};
e=b.extend({fn:b.noop,json_payload:null,jsonp:!0,"return":!1,ssl:null,timeout:null},e);"string"===typeof e.fn?(f=window[e.fn],l=e.fn):"function"===typeof e.fn&&(f=e.fn);"function"===b.type(f)&&(d=b.entryPoint(b.destructing(function(){var a,d;e.json_payload&&(d=e.json_payload,a=b.fromJSON(c[d]),c=b.extend(c,a),delete c[d]);f({response:b.toArray(arguments),data:g,args:c});window[l]&&(window[l]=void 0)})),null!==e.timeout&&setTimeout(d,e.timeout));e.json_payload&&b.traits.cors&&(c=h(c,e.json_payload));
!0===e.jsonp&&(window[l]=d,c=b.extend({format:"jsonp",jsonp:l},c));h=b.toQuery(c);return e["return"]?r(a,h,e.ssl):b.traits.json&&b.traits.cors&&b.cors(r(a,"",e.ssl),h,e.jsonp?null:d)?!0:b.jsonp(r(a,h,e.ssl))},apiCallback:function(a,c){return function(e){"string"===b.type(e)&&(e={response:[e]});a.apply(c,e.response.concat(e.data))}},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},some:function(a,c){return Boolean(b.find(a,function(a){return c(a)}))},stopPropagation:function(a){a&&
a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},time:function(){return(new Date).getTime()},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,f,d=[];b=0;for(f=a.length;b<f;b++)d[b]=a[b];return d}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,
c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,e){b.contains(a,e)||a.push(e);return a})},unlink:function(a){var c,b=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)b.appendChild(c);a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a)}},withScope:function(){var a=function(a,e,f){if(f.self&&b.contains(e,a))return a;if(f.ancestors)return b.find(b.ancestors(a).slice(0),
function(a){return b.contains(e,a)},{timeout:!0})};return function(c,e,f){var d=b.select(e);f=b.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},f);c=b.all(b.map(c,function(c){var e,g=[];(e=a(c,d,f))?g.push(e):1===c.nodeType&&f.descendants&&b.each(d,function(a){b.contains(b.ancestors(a),c)&&g.push(a)},{timeout:!0});return[c,g]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?b.reduce([],c,function(a,c){return a.concat(c[1])}):c}}()});var q=function(){var a=
b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};q.amd=!0;(function(a){function c(a,c,b,e){var f,d,h,g,l;(c?c.ownerDocument||c:C)!==z&&I(c);c=c||z;b=b||[];if(!a||"string"!==typeof a)return b;if(1!==(g=c.nodeType)&&9!==g)return[];if(E&&!e){if(f=ra.exec(a))if(h=f[1])if(9===g)if((d=c.getElementById(h))&&d.parentNode){if(d.id===h)return b.push(d),b}else return b;else{if(c.ownerDocument&&(d=c.ownerDocument.getElementById(h))&&S(c,d)&&d.id===h)return b.push(d),b}else{if(f[2])return J.apply(b,
c.getElementsByTagName(a)),b;if((h=f[3])&&v.getElementsByClassName&&c.getElementsByClassName)return J.apply(b,c.getElementsByClassName(h)),b}if(v.qsa&&(!A||!A.test(a))){d=f=x;h=c;l=9===g&&a;if(1===g&&"object"!==c.nodeName.toLowerCase()){g=T(a);(f=c.getAttribute("id"))?d=f.replace(sa,"\\$&"):c.setAttribute("id",d);d="[id='"+d+"'] ";for(h=g.length;h--;)g[h]=d+k(g[h]);h=ea.test(a)&&m(c.parentNode)||c;l=g.join(",")}if(l)try{return J.apply(b,h.querySelectorAll(l)),b}catch(r){}finally{f||c.removeAttribute("id")}}}return ja(a.replace(Y,
"$1"),c,b,e)}function b(){function a(b,e){c.push(b+" ")>t.cacheLength&&delete a[c.shift()];return a[b+" "]=e}var c=[];return a}function f(a){a[x]=!0;return a}function d(a){var c=z.createElement("div");try{return!!a(c)}catch(b){return!1}finally{c.parentNode&&c.parentNode.removeChild(c)}}function g(a,c){for(var b=a.split("|"),e=a.length;e--;)t.attrHandle[b[e]]=c}function l(a,c){var b=c&&a,e=b&&1===a.nodeType&&1===c.nodeType&&(~c.sourceIndex||ka)-(~a.sourceIndex||ka);if(e)return e;if(b)for(;b=b.nextSibling;)if(b===
c)return-1;return a?1:-1}function n(a){return function(c){return"input"===c.nodeName.toLowerCase()&&c.type===a}}function r(a){return function(c){var b=c.nodeName.toLowerCase();return("input"===b||"button"===b)&&c.type===a}}function s(a){return f(function(c){c=+c;return f(function(b,e){for(var f,d=a([],b.length,c),h=d.length;h--;)if(b[f=d[h]])b[f]=!(e[f]=b[f])})})}function m(a){return a&&typeof a.getElementsByTagName!==O&&a}function u(){}function k(a){for(var c=0,b=a.length,e="";c<b;c++)e+=a[c].value;
return e}function p(a,c,b){var e=c.dir,f=b&&"parentNode"===e,d=ta++;return c.first?function(c,b,d){for(;c=c[e];)if(1===c.nodeType||f)return a(c,b,d)}:function(c,b,h){var X,g,da=[D,d];if(h)for(;c=c[e];){if((1===c.nodeType||f)&&a(c,b,h))return!0}else for(;c=c[e];)if(1===c.nodeType||f){g=c[x]||(c[x]={});if((X=g[e])&&X[0]===D&&X[1]===d)return da[2]=X[2];g[e]=da;if(da[2]=a(c,b,h))return!0}}}function B(a){return 1<a.length?function(c,b,e){for(var f=a.length;f--;)if(!a[f](c,b,e))return!1;return!0}:a[0]}
function Z(a,c,b,e,f){for(var d,h=[],g=0,l=a.length,r=null!=c;g<l;g++)if(d=a[g])if(!b||b(d,e,f))h.push(d),r&&c.push(g);return h}function fa(a,b,e,d,h,g){d&&!d[x]&&(d=fa(d));h&&!h[x]&&(h=fa(h,g));return f(function(f,g,l,r){var s,n,m=[],y=[],w=g.length,k;if(!(k=f)){k=b||"*";for(var u=l.nodeType?[l]:l,R=[],p=0,qa=u.length;p<qa;p++)c(k,u[p],R);k=R}k=a&&(f||!b)?Z(k,m,a,l,r):k;u=e?h||(f?a:w||d)?[]:g:k;e&&e(k,u,l,r);if(d){s=Z(u,y);d(s,[],l,r);for(l=s.length;l--;)if(n=s[l])u[y[l]]=!(k[y[l]]=n)}if(f){if(h||
a){if(h){s=[];for(l=u.length;l--;)if(n=u[l])s.push(k[l]=n);h(null,u=[],s,r)}for(l=u.length;l--;)if((n=u[l])&&-1<(s=h?M.call(f,n):m[l]))f[s]=!(g[s]=n)}}else u=Z(u===g?u.splice(w,u.length):u),h?h(null,g,u,r):J.apply(g,u)})}function U(a){var c,b,e,f=a.length,d=t.relative[a[0].type];b=d||t.relative[" "];for(var h=d?1:0,g=p(function(a){return a===c},b,!0),l=p(function(a){return-1<M.call(c,a)},b,!0),r=[function(a,b,e){return!d&&(e||b!==$)||((c=b).nodeType?g(a,b,e):l(a,b,e))}];h<f;h++)if(b=t.relative[a[h].type])r=
[p(B(r),b)];else{b=t.filter[a[h].type].apply(null,a[h].matches);if(b[x]){for(e=++h;e<f&&!t.relative[a[e].type];e++);return fa(1<h&&B(r),1<h&&k(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(Y,"$1"),b,h<e&&U(a.slice(h,e)),e<f&&U(a=a.slice(e)),e<f&&k(a))}r.push(b)}return B(r)}function ua(a,b){var e=0<b.length,d=0<a.length,h=function(f,h,g,l,r){var s,n,m,y=0,w="0",u=f&&[],k=[],R=$,p=f||d&&t.find.TAG("*",r),ia=D+=null==R?1:Math.random()||0.1,B=p.length;for(r&&($=h!==z&&h);w!==B&&null!=
(s=p[w]);w++){if(d&&s){for(n=0;m=a[n++];)if(m(s,h,g)){l.push(s);break}r&&(D=ia)}e&&((s=!m&&s)&&y--,f&&u.push(s))}y+=w;if(e&&w!==y){for(n=0;m=b[n++];)m(u,k,h,g);if(f){if(0<y)for(;w--;)!u[w]&&!k[w]&&(k[w]=va.call(l));k=Z(k)}J.apply(l,k);r&&(!f&&0<k.length&&1<y+b.length)&&c.uniqueSort(l)}r&&(D=ia,$=R);return u};return e?f(h):h}var P,v,t,aa,la,T,ga,ja,$,K,Q,I,z,F,E,A,N,ba,S,x="sizzle"+-new Date,C=a.document,D=0,ta=0,ma=b(),na=b(),oa=b(),ha=function(a,c){a===c&&(Q=!0);return 0},O="undefined",ka=-2147483648,
wa={}.hasOwnProperty,L=[],va=L.pop,xa=L.push,J=L.push,pa=L.slice,M=L.indexOf||function(a){for(var c=0,b=this.length;c<b;c++)if(this[c]===a)return c;return-1},Y=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,ya=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,za=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Aa=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ba=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Ca=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ca={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Da=/^(?:input|select|textarea|button)$/i,Ea=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,ra=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,sa=/'|\\/g,G=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,H=function(a,c,b){a="0x"+c-65536;return a!==a||b?c:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{J.apply(L=pa.call(C.childNodes),C.childNodes),L[C.childNodes.length].nodeType}catch(Fa){J={apply:L.length?function(a,c){xa.apply(a,pa.call(c))}:function(a,c){for(var b=
a.length,e=0;a[b++]=c[e++];);a.length=b-1}}}v=c.support={};la=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};I=c.setDocument=function(a){var c=a?a.ownerDocument||a:C;a=c.defaultView;if(c===z||9!==c.nodeType||!c.documentElement)return z;z=c;F=c.documentElement;E=!la(c);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){I()},!1):a.attachEvent&&a.attachEvent("onunload",function(){I()}));v.attributes=d(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=d(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=V.test(c.getElementsByClassName)&&d(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=d(function(a){F.appendChild(a).id=x;return!c.getElementsByName||!c.getElementsByName(x).length});v.getById?(t.find.ID=function(a,c){if(typeof c.getElementById!==O&&E){var b=
c.getElementById(a);return b&&b.parentNode?[b]:[]}},t.filter.ID=function(a){var c=a.replace(G,H);return function(a){return a.getAttribute("id")===c}}):(delete t.find.ID,t.filter.ID=function(a){var c=a.replace(G,H);return function(a){return(a=typeof a.getAttributeNode!==O&&a.getAttributeNode("id"))&&a.value===c}});t.find.TAG=v.getElementsByTagName?function(a,c){if(typeof c.getElementsByTagName!==O)return c.getElementsByTagName(a)}:function(a,c){var b,e=[],f=0,d=c.getElementsByTagName(a);if("*"===a){for(;b=
d[f++];)1===b.nodeType&&e.push(b);return e}return d};t.find.CLASS=v.getElementsByClassName&&function(a,c){if(typeof c.getElementsByClassName!==O&&E)return c.getElementsByClassName(a)};N=[];A=[];if(v.qsa=V.test(c.querySelectorAll))d(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),d(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(v.matchesSelector=V.test(ba=F.matches||F.webkitMatchesSelector||F.mozMatchesSelector||F.oMatchesSelector||F.msMatchesSelector))&&
d(function(a){v.disconnectedMatch=ba.call(a,"div");ba.call(a,"[s!='']:x");N.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));N=N.length&&RegExp(N.join("|"));
S=(a=V.test(F.compareDocumentPosition))||V.test(F.contains)?function(a,c){var b=9===a.nodeType?a.documentElement:a,e=c&&c.parentNode;return a===e||!(!e||!(1===e.nodeType&&(b.contains?b.contains(e):a.compareDocumentPosition&&a.compareDocumentPosition(e)&16)))}:function(a,c){if(c)for(;c=c.parentNode;)if(c===a)return!0;return!1};ha=a?function(a,b){if(a===b)return Q=!0,0;var e=!a.compareDocumentPosition-!b.compareDocumentPosition;if(e)return e;e=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):
1;return e&1||!v.sortDetached&&b.compareDocumentPosition(a)===e?a===c||a.ownerDocument===C&&S(C,a)?-1:b===c||b.ownerDocument===C&&S(C,b)?1:K?M.call(K,a)-M.call(K,b):0:e&4?-1:1}:function(a,b){if(a===b)return Q=!0,0;var e,f=0;e=a.parentNode;var d=b.parentNode,h=[a],W=[b];if(!e||!d)return a===c?-1:b===c?1:e?-1:d?1:K?M.call(K,a)-M.call(K,b):0;if(e===d)return l(a,b);for(e=a;e=e.parentNode;)h.unshift(e);for(e=b;e=e.parentNode;)W.unshift(e);for(;h[f]===W[f];)f++;return f?l(h[f],W[f]):h[f]===C?-1:W[f]===
C?1:0};return c};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&I(a);b=b.replace(Aa,"='$1']");if(v.matchesSelector&&E&&(!N||!N.test(b))&&(!A||!A.test(b)))try{var e=ba.call(a,b);if(e||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(f){}return 0<c(b,z,null,[a]).length};c.contains=function(a,c){(a.ownerDocument||a)!==z&&I(a);return S(a,c)};c.attr=function(a,c){(a.ownerDocument||a)!==z&&I(a);var b=t.attrHandle[c.toLowerCase()],
b=b&&wa.call(t.attrHandle,c.toLowerCase())?b(a,c,!E):void 0;return void 0!==b?b:v.attributes||!E?a.getAttribute(c):(b=a.getAttributeNode(c))&&b.specified?b.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var c,b=[],e=0,f=0;Q=!v.detectDuplicates;K=!v.sortStable&&a.slice(0);a.sort(ha);if(Q){for(;c=a[f++];)c===a[f]&&(e=b.push(f));for(;e--;)a.splice(b[e],1)}K=null;return a};aa=c.getText=function(a){var c,b="",e=0;if(c=a.nodeType)if(1===
c||9===c||11===c){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=aa(a)}else{if(3===c||4===c)return a.nodeValue}else for(;c=a[e++];)b+=aa(c);return b};t=c.selectors={cacheLength:50,createPseudo:f,match:ca,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(G,H);a[3]=(a[3]||a[4]||a[5]||"").replace(G,H);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var c,b=!a[6]&&a[2];if(ca.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(b&&Ba.test(b)&&(c=T(b,!0))&&(c=b.indexOf(")",b.length-c)-b.length))a[0]=a[0].slice(0,c),a[2]=b.slice(0,c);return a.slice(0,3)}},filter:{TAG:function(a){var c=
a.replace(G,H).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===c}},CLASS:function(a){var c=ma[a+" "];return c||(c=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return c.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==O&&a.getAttribute("class")||"")})},ATTR:function(a,b,e){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===e:"!="===b?
f!==e:"^="===b?e&&0===f.indexOf(e):"*="===b?e&&-1<f.indexOf(e):"$="===b?e&&f.slice(-e.length)===e:"~="===b?-1<(" "+f+" ").indexOf(e):"|="===b?f===e||f.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,c,b,e,f){var d="nth"!==a.slice(0,3),h="last"!==a.slice(-4),g="of-type"===c;return 1===e&&0===f?function(a){return!!a.parentNode}:function(c,b,l){var r,s,n,w,y;b=d!==h?"nextSibling":"previousSibling";var m=c.parentNode,k=g&&c.nodeName.toLowerCase();l=!l&&!g;if(m){if(d){for(;b;){for(s=c;s=s[b];)if(g?s.nodeName.toLowerCase()===
k:1===s.nodeType)return!1;y=b="only"===a&&!y&&"nextSibling"}return!0}y=[h?m.firstChild:m.lastChild];if(h&&l){l=m[x]||(m[x]={});r=l[a]||[];w=r[0]===D&&r[1];n=r[0]===D&&r[2];for(s=w&&m.childNodes[w];s=++w&&s&&s[b]||(n=w=0)||y.pop();)if(1===s.nodeType&&++n&&s===c){l[a]=[D,w,n];break}}else if(l&&(r=(c[x]||(c[x]={}))[a])&&r[0]===D)n=r[1];else for(;s=++w&&s&&s[b]||(n=w=0)||y.pop();)if((g?s.nodeName.toLowerCase()===k:1===s.nodeType)&&++n)if(l&&((s[x]||(s[x]={}))[a]=[D,n]),s===c)break;n-=f;return n===e||
0===n%e&&0<=n/e}}},PSEUDO:function(a,b){var e,d=t.pseudos[a]||t.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return d[x]?d(b):1<d.length?(e=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var e,f=d(a,b),h=f.length;h--;)e=M.call(a,f[h]),a[e]=!(c[e]=f[h])}):function(a){return d(a,0,e)}):d}},pseudos:{not:f(function(a){var c=[],b=[],e=ga(a.replace(Y,"$1"));return e[x]?f(function(a,c,b,f){f=e(a,null,f,[]);for(var d=a.length;d--;)if(b=f[d])a[d]=!(c[d]=b)}):
function(a,f,d){c[0]=a;e(c,null,d,b);return!b.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(G,H);return function(c){return-1<(c.textContent||c.innerText||aa(c)).indexOf(a)}}),lang:f(function(a){Ca.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(G,H).toLowerCase();return function(c){var b;do if(b=E?c.lang:c.getAttribute("xml:lang")||c.getAttribute("lang"))return b=b.toLowerCase(),b===a||0===b.indexOf(a+"-");while((c=c.parentNode)&&
1===c.nodeType);return!1}}),target:function(c){var b=a.location&&a.location.hash;return b&&b.slice(1)===c.id},root:function(a){return a===F},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&!!a.checked||"option"===c&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Ea.test(a.nodeName)},input:function(a){return Da.test(a.nodeName)},button:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&"button"===a.type||"button"===c},text:function(a){var c;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(c=a.getAttribute("type"))||"text"===c.toLowerCase())},first:s(function(){return[0]}),
last:s(function(a,c){return[c-1]}),eq:s(function(a,c,b){return[0>b?b+c:b]}),even:s(function(a,c){for(var b=0;b<c;b+=2)a.push(b);return a}),odd:s(function(a,c){for(var b=1;b<c;b+=2)a.push(b);return a}),lt:s(function(a,c,b){for(c=0>b?b+c:b;0<=--c;)a.push(c);return a}),gt:s(function(a,c,b){for(b=0>b?b+c:b;++b<c;)a.push(b);return a})}};t.pseudos.nth=t.pseudos.eq;for(P in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[P]=n(P);for(P in{submit:!0,reset:!0})t.pseudos[P]=r(P);u.prototype=t.filters=
t.pseudos;t.setFilters=new u;T=c.tokenize=function(a,b){var e,f,d,h,g,l,r;if(g=na[a+" "])return b?0:g.slice(0);g=a;l=[];for(r=t.preFilter;g;){if(!e||(f=ya.exec(g)))f&&(g=g.slice(f[0].length)||g),l.push(d=[]);e=!1;if(f=za.exec(g))e=f.shift(),d.push({value:e,type:f[0].replace(Y," ")}),g=g.slice(e.length);for(h in t.filter)if((f=ca[h].exec(g))&&(!r[h]||(f=r[h](f))))e=f.shift(),d.push({value:e,type:h,matches:f}),g=g.slice(e.length);if(!e)break}return b?g.length:g?c.error(a):na(a,l).slice(0)};ga=c.compile=
function(a,c){var b,e=[],f=[],d=oa[a+" "];if(!d){c||(c=T(a));for(b=c.length;b--;)d=U(c[b]),d[x]?e.push(d):f.push(d);d=oa(a,ua(f,e));d.selector=a}return d};ja=c.select=function(a,c,b,e){var f,d,h,g,l="function"===typeof a&&a,r=!e&&T(a=l.selector||a);b=b||[];if(1===r.length){d=r[0]=r[0].slice(0);if(2<d.length&&"ID"===(h=d[0]).type&&v.getById&&9===c.nodeType&&E&&t.relative[d[1].type]){if(c=(t.find.ID(h.matches[0].replace(G,H),c)||[])[0])l&&(c=c.parentNode);else return b;a=a.slice(d.shift().value.length)}for(f=
ca.needsContext.test(a)?0:d.length;f--;){h=d[f];if(t.relative[g=h.type])break;if(g=t.find[g])if(e=g(h.matches[0].replace(G,H),ea.test(d[0].type)&&m(c.parentNode)||c)){d.splice(f,1);a=e.length&&k(d);if(!a)return J.apply(b,e),b;break}}}(l||ga(a,r))(e,c,!E,b,ea.test(a)&&m(c.parentNode)||c);return b};v.sortStable=x.split("").sort(ha).join("")===x;v.detectDuplicates=!!Q;I();v.sortDetached=d(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});d(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,c,b){if(!b)return a.getAttribute(c,"type"===c.toLowerCase()?1:2)});(!v.attributes||!d(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&g("value",function(a,c,b){if(!b&&"input"===a.nodeName.toLowerCase())return a.defaultValue});d(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,c,b){var e;if(!b)return!0===a[c]?c.toLowerCase():(e=a.getAttributeNode(c))&&e.specified?e.value:null});"function"===typeof q&&q.amd?q(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(e,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,firefox:c.firefox,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie||c.firefox)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,
c){return this.regexp(c).test(a)},redact:function(a,c){return a.replace(this.regexp(c),"___")},regexp:function(c){c=b.extend({},c);var f=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,c){return this.contains(a+" "+document.referrer,c||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full",scope:"body",
spec:{selector:"body"}},bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},
vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},
c={getPostId:function(a){var c,d;if(this===b.platforms.NONE)return" ";d=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=d[a]?d[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];!a&&(document&&document.body)&&(a=[document.body]);
a&&this.spec&&(c=b.unique(b.reduce([],b.withScope(a,this.spec.selector),function(a,c){return a.concat(c[1])})));return c}};b.each(a,function(e,f){e.id=e.id||f;b.each(c,function(a,c){e[c]=b.bind(a,e)});a[f]=e});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(c){return c.id===a})};return a}();b.observer=function(){var a=[],c=0,e=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,d){if(c.document&&
b.traits.mutation){var g={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var e=[];"characterData"===a.type?a.target&&(e=[a.target]):a.addedNodes&&a.addedNodes.length&&(e=b.toArray(a.addedNodes));e.length&&(c=c.concat(e))});0<c.length&&d(c)}))};a.push(g);e(g)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,e)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&
void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,fastRegexp:!b.browser.firefox,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,performanceTiming:Boolean(window.performance&&window.performance.timing),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var g,
m,n,p;d={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],rels:["norewrite"],tags:"applet embed object head img input link meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a,c,e,f=function(){var a={optimize:"content",domains:"content"};return function(c,e,f){var d=b.toArray(arguments).slice(3,arguments.length),h=a[c];Boolean(h)&&(f=b.extend({},f,{json_payload:h}));var h=
c,l=n(f),m;m=b.extend(b.commonParams(c,g),e);m.subId&&m.key!==g.key&&(m.subId=null);return{data:d,method:h,opts:l,params:m}}}(),d=function(a){var c={},e={};b.each(a,function(a){var f=a[0],d=a[1],h=a[2];a=b.toArray(a).slice(3,a.length);e[f]=b.mergeParams(e[f]||b.commonParams(f,g),d);c[f]=c[f]||[];c[f].push({opts:n(h),data:a})});return{calls:c,params:e}},n=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(e){var f,d=e.response?e.response[0]:null;"object"===b.type(d)&&
("array"===b.type(d.crawl)&&"object"===b.type(p.crawler)&&"function"===b.type(p.crawler.crawl))&&(f=b.map(d.crawl,function(a){return a+""}),delete d.crawl,p.crawler.crawl(f));return c.apply(a,arguments)}}(a.fn));return a},l=function(a){return b.request.apply(b,[g.api_url+"/"+a.method,a.params,a.opts].concat(a.data))},m=function(a,c,e){b.each(c,function(c){c&&(c.opts&&c.opts.fn&&a)&&c.opts.fn({response:b.packageArgs(a),data:c.data,args:e})})};a=function(){var a=function(a){var c=a.data[0].params,e=
a.data[0].calls;a=b.fromJSON(a.response[0])||{};b.each(a,function(a,f){var d=c[f],h=e[f],g;if("string"===b.type(a)&&(g=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(g[1]);m(a,h,d)})};return function(c){c=d(c,!0);l({data:c,method:"batch",params:b.extend(b.commonParams("batch",g),c.params),opts:{json_payload:"batch",jsonp:!1,fn:b.bind(a,window)}})}}();c=function(a,c,e){var g=d(a,!1);a=b.reduce({},g.calls[e],function(a,c){return{jsonp:a.jsonp||!c.opts||!1!==c.opts.jsonp,ssl:a.ssl||!c.opts||!1!==c.opts.ssl}});
return l(f(c,g.params[c],{fn:function(a){m(a.response[0],g.calls[c],g.params[c])},jsonp:a.jsonp,ssl:a.ssl},g))};e=function(){return l(f.apply(this,arguments))};return b.batchable(function(){var f,d;return b.batched(arguments)?(f=b.batchArgs(arguments),d=b.batchCallType(f),"batch"===d?a.call(this,f):c.call(this,f,d)):e.apply(this,arguments)},function(){return{batch:g.batch_calls,timeout:g.batch_call_timeout}})}(),addEventListener:function(a,c){this.fire(a,c)},click:function(){var a=function(a,c){if("_self"===
c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var d=a.open("",c);d.focus();return d}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],l=function(a,c){for(var b=a,e=b.data;(b=b[c+"Sibling"])&&3===b.nodeType;)e+=b.data;return e},n=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-
1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?l(c,"previous"):"",g[2]=h&&3===h.nodeType?l(h,"next"):"",g=n.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),
v:2},d.log("info",b.toQuery(a))))};return function(e,f){var d,n,l,m,r=b.context(e)||window;f=e.target||f;f=!f||f===r.name||"_top"===f&&r.top===r||"_parent"===f&&r.parent===r?"_self":f;l=a(r,f);if("_self"!==f&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))m="go";else try{if(void 0===l.document)throw!0;m="jsonp"}catch(s){m="go"}d=b.destructing(b.apiCallback(function(){g.time_api&&this.logEvent.stop("clk");var a=b.toArray(arguments);a.unshift(e,l,f);this.onApiClick.apply(this,
a)},this));b.cache(this,"link","string"===typeof e?e:b.getActualHref(e));if("string"===typeof e&&(e=b.createA(e,f),!this.processLink(e))||!g.enabled)return d();n=this.clickParams(e,m);g.time_api&&this.logEvent.start("clk");g.log_context&&c(e);if("go"===m)this.redirect(this.api.now("click",n,{"return":!0}),r,l,f);else if(l===r)this.api.now("click",n,{fn:d,timeout:g.click_timeout});else{if(b.contextIsAncestor(r,l))return this.redirect(b.getActualHref(e),r,l,f);d=b.entryPoint(d);setTimeout(function(){d()},
g.click_timeout);l.document.open();l.callback=d;l.document.write("<html><head><title>"+b.getActualHref(e)+'</title><script type="text/javascript" src="'+this.api.now("click",n,{fn:"callback","return":!0})+'">\x3c/script></head></html>');l.document.close()}}}(),clickParams:function(a,c){var e=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:g.reaffiliate||null,title:window.document.title,txt:a.innerHTML,loAsUuid:b.cache(a,"uuid")||null,rewrit:b.cache(a,
"rewrit")});128<e.txt.length&&(e.txt=e.txt.replace(/<[^>]+>/g,""),e.txt=128<e.txt.length?e.txt.substr(0,125)+"...":e.txt);return e},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,c){function b(a,c){0==n||1E3<c?a(0==n&&g):setTimeout(function(){b(a,2*c)},2*c)}function d(){--n||(g=!m&&s)}var g=!1,n=2,m=!1,s=!1;if("function"==typeof c){a+="?ch=*&rn=*";var k=11*Math.random(),p=new Image;p.onload=d;p.onerror=function(){m=!0;d()};p.src=a.replace(/\*/,1).replace(/\*/,k);
p=new Image;p.onload=d;p.onerror=function(){s=!0;d()};p.src=a.replace(/\*/,2).replace(/\*/,k);b(c,250)}}}}catch(c){a={detect:function(a,c){c(!0)}}}return function(c){var d=b.updateUrl(g.asset_url,{pathname:"/images/pixel.gif"});a.detect(d,c)}}(),enabled:function(){if(g.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))g.enabled=!1;return g.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!p[a]){var e=p,f;f=c;f="function"===b.type(f)?b.entryPoint(b.bind(f,
d)):f;e[a]=f}}}(),fire:function(){var a={};return function(c,e){c=c.toLowerCase();var d=a[c]||{fired:!1,listeners:[]};"function"===typeof e?d.fired?setTimeout(function(){e({type:c})},0):d.listeners.push(e):(d.fired=!0,b.each(d.listeners,function(a){"function"===typeof a&&a({type:c})}),d.listeners=[]);a[c]=d}}(),handleRightClick:function(a,c){if(g.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});
setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return g.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;m={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(e){}b.exceptionLogger(b.bind(c.logException,c),!g.dev);b.each(g.script_timeout);return b.entryPoint(function(){c.initProcessors();
c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);p=n[k]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("api_now",b.bind(this.api.now,this.api));
this.expose("harmony");this.expose("opt");this.expose("platform");this.expose("registerProcessor",function(){if(0<arguments.length)return d.registerProcessor.apply(d,arguments)});this.expose("sendLinks");b.extend(p,p===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;g.dr_key=window.DR_id;
this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=void 0}})},initEvents:function(a){var c=b.traits.windowLevelHandlers?a:a.document,e=function(c){c=c||a.event;if((c=b.eventLink(c))&&!b.cache(c,"evented"))n(d.EVENT_LEVEL_LINK,c),b.cache(c,"evented",!0)},f=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,c){return a.concat(c)}));a=b.all(b.unique(a),
function(a){return Boolean(a.parentNode)&&d.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a[href]",{ancestors:!1}),function(a){d.processLinks(a[1])}),b.each(m,function(c,b){c.opts.mode!==d.PLUGIN_MANUAL&&d.runPlugin(b,a)}))},function(){return{batch:g.batch_mutation,timeout:g.batch_mutation_timeout}}))},h=function(a,c){return function(){var e=[a].concat(b.toArray(arguments));c.apply(d,e)}},n=function(a,c){b.on(c,"click",h(a,d.onClick));b.on(c,"contextmenu",h(a,d.onContextmenu))};if(g.dynamic)b.on("DOMReady",
function(){f(a)});b.on(c,"copy",b.bind(d.onCopy,d));b.on(c,"mousedown",e);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",e)})});(!b.traits.quirksMode||d.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&n(d.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(p[c[a]]=window[a],"vglnk_domain"===a&&(p[c[a]]+="/api"))},
initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){g.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(d);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(k="vglnk");var a=window,c=k.split("."),b;for(k=c.pop();0<c.length;)b=
c.shift(),a[b]=a[b]||{},a=a[b];n=a;p=n[k]=n[k]||{}},initOptions:function(){var a;this.initLegacyOptions();g=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:b.harmony.DEFAULT,link_target:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),g,p,{batch_calls:!0,
batch_call_timeout:100,batch_links:!1,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,links_version:3.2,log_context:!0,links_merge_timeout:75,nofollow:{},norewrite:{},script_timeout:2E3,time_log_timeout:3E3,time_api:!1,time_load:!1,testing_js:[],plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});for(a in g)"_plugin"===a.substr(-7)&&delete g[a]},initPlugins:function(){var a,c=1,e={link_affiliation:"convert",link_optimization:"optimize",
page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=["spotlight"],h=["harmony"],n=function(b){return function(b){return function(){delete m[b].opts.mode;c=1;clearTimeout(a);k()}}(b)},l=function(a){var c;b.find(e,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:g.key,link_phrases:!1});a[c].link_urls=g.link_urls;return a},k=function(){var e={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},f=function(a,
c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,e,a.setup(a.opts,b.clone(b),p,l(g.key))),a["public"]&&d.expose(c,a["public"],!1)),a.opts.mode!==d.PLUGIN_MANUAL&&d.runPlugin(c))},l=function(a){var c=function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);d.log.apply(this,c)}};c.event=d.logEvent;return c},n=function(a){return!Boolean(a._ran)};a=null;b.each(h,function(a){var c=m[a];c&&!Boolean(c._ran)&&
f(c,a)});b.each(b.all(m,n),f);b.find(m,n)&&(a=setTimeout(b.entryPoint(k),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},r=function(){setTimeout(function(){d.api.flush()},100);k();b.on("DOMReady",function(){setTimeout(d.api.flush,0)})};return function(a){a=l(a);b.each(a,b.bind(function(a,c){c=e[c]||c;"object"===typeof a&&!1!==a.enabled&&(m[c]={opts:a},b.contains(f,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,n(c)))},this));r()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;
c=b.createA(g.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){g.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,
""),a.target="_blank")})},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.commercial)&&g.commercial[a]},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var f=b.canonicalizeHostname(c),h="",n=!1;try{h=c.protocol,f.charAt(0)}catch(l){return!0}n=Boolean(""===f||!h.match(/^https?:$/i)||g.norewrite[f]);if(h=!n)var h=b.cache(c,"type"),m=b.cache(c,"params")||{},h=!Boolean(h||m.type);h&&(n=Boolean(a===
f||!g.rewrite_original||!g.rewrite_any&&!d.isCommercial(c)));return n}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,c,e,d){var h,n=b.toQuery({libId:g.library_id,nocache:b.uniqid()});h="pixel.gif";if("custom"===a)n+="&"+b.toQuery({key:c,type:e}),b.each("array"===b.type(d)?d:[d],function(a){b.each(["e","i","o"],function(c){delete a[c]});n+="&"+b.toQuery(a)});else{n+="&"+b.toQuery({key:g.key,drKey:g.key?null:g.dr_key,subId:g.sub_id});if("time"===a&&b.traits.json)h=
"time.gif",a={e:b.toJSON(c),v:2};else if("exception"===a)a={e:c,o:e};else if("info"===a)a={i:c};else return;n+="&"+b.toQuery(a)}h=g.api_url+"/"+h+"?"+n;b.pii.transmits(h)||(b.createEl("img").src=h)},logEvent:function(){var a={},c=b.time(),e=b.traits.performanceTiming?window.performance.timing.domLoading:null,f=b.batchable(function(){var a;a=b.batched(arguments)?b.batchArgs(arguments):[arguments];a=b.map(a,function(a){return b.prune({event:a[0],time:a[1],total:a[2]})});a.length&&d.log("time",a)},function(){return{timeout:g.time_log_timeout}});
return{start:function(c){a[c]=a[c]||{logged:0,times:[]};a[c].times.push(b.time())},stop:function(c){var d,g,n=b.time();a[c]&&(a[c].times&&a[c].times.length)&&(d=a[c].times.shift(),g=e&&0===a[c].logged?n-e:null,a[c].logged+=1,f(c,n-d,g))},load:function(){e&&f("load",c-e)}}}(),logException:function(a){if(g.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},onApiClick:function(a,
c,e,d,h){var n=d||b.getActualHref(a),l=b.bind(function(){this.redirect(n,b.context(a),c,e)},this);"object"===typeof h&&(h.tracking||h.image)?(d=b.createEl(h.tracking?"iframe":"img",{src:h.tracking||h.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(d),setTimeout(b.entryPoint(l),h.timeout||g.hop_timeout)):l()},onApiPing:function(a,c,e,f,h,n){g.rewrite_original=!1;h=b.reformatKeys(h||{});var l,m;f=function(a){var c={},e=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&
b.each(a,e);return c};m=b.extend(g.plugins,h.plugins);g=b.extend(g,h);delete g.plugins;g.click_timeout=c;g.library_id=a;h.time&&(g.time_api=g.time_load=h.time);g.time_api&&this.logEvent.stop("png");g.time_load&&this.logEvent.load();"array"===b.type(g.testing_js)&&0<g.testing_js.length&&b.each(g.testing_js,function(a){b.jsonp(a)});b.extend(g.nofollow,f(n));b.extend(g.norewrite,f(e));for(l in g)"on"===l.toLowerCase().substr(0,2)&&(2<l.length&&"function"===b.type(g[l]))&&(b.on(d,l.toLowerCase().substr(2),
b.bind(g[l],window)),delete g[l]);this.initPlugins(m);this.initContext(window);this.fire("libready")},onClick:function(a,c){c=c||window.event;var e=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,d=c.which&&1===c.which||0===c.button,h=b.eventLink(c);if(h&&d&&!e&&!b.isDefaultPrevented(c)&&this.isRewritable(h)&&this.shouldHandleClick(a,h))return this.click(h),b.preventDefault(c)},onContextmenu:function(a,c){var e=b.eventLink(c||window.event);e&&(this.isRewritable(e)&&this.shouldHandleClick(a,e))&&this.handleRightClick(e,
"setup")},onCopy:function(a){var c,e,f,h=[];if(window.getSelection){e=window.getSelection();a=0;for(c=e.rangeCount;a<c;a++){try{f=e.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<f.length&&128>=f.length&&h.push(f)}}b.each(h,function(a){d.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(g[a]=c);return g[a]},ping:function(){var a=!1;return function(){if(!a&&(g.key||g.dr_key)){var c=
{ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logEvent.start("png"),this.detectFiltering(b.bind(function(a){a&&(g.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.apiCallback(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(g.platform)||b.platforms.NONE},processLink:function(a){var c=b.cache(a,"processors")||{},e=this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(e||
b.opts.any)&&b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,e,d){c=c||window.top;!b.traits.crossWindowCommunication&&!e?(d=c.open(a,d),d.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.entryPoint(function(){!e||e===c?c.location=a:b.contextIsAncestor(c,e)?e.location=a:e.location.replace(a)}),
0):("_blank"===d&&(d=b.uniqid("win_")),d=b.createA(a,d),d.rel="norewrite",c.document.body.appendChild(d),d.click(),d.parentNode.removeChild(d))},runPlugin:function(a,c){var e=window.document,d=m[a];if(d&&d.initDocuments){if(c)d.initNodes(c);else if(d.init(),"function"===b.type(d.initDocuments)&&"document"===b.type(e)&&d.initDocuments([e]),"function"===b.type(d.initNodes)&&"element"===b.type(e.body))b.on("DOMReady",function(){d.initNodes([e.body])});d._ran=!0}},registerProcessor:function(){var a=!1,
c=[],e=function(e,d){if(void 0===e)return c;"function"===b.type(e)&&(d=b.extend({any:!1},d),c.push({fn:e,id:b.uniqid(),opts:d}),a&&this.initLinks())};e(function(){a=!0});return e}(),sendLinks:b.mergeable(function(){return{batchFn:d.api,nonBatchFn:d.api.now,batchable:g.batch_links,timeout:g.links_merge_timeout}}),shouldHandleClick:function(a,c){var e=!0;a===this.EVENT_LEVEL_LINK&&(e=this.harmony(b.harmony.LINK_EVENTS)||this.isCommercial(c)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return e}};
d.init();try{delete window.vglnk_self}catch(B){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(k,d,b){var q={},g,m;k=d.extend({any:!0,convert_minimum_bid:!1},k);m={getDomains:function(){var g=[];d.each(q,function(b,d){2!==q[d]&&(g.push(d),q[d]=2)});0<g.length&&b.api("domains",{domains:g.join("|"),v:"2"},{fn:d.apiCallback(m.onDomainApi,m)})},init:function(){b.opt("link_target",k.link_target);b.opt("rewrite_any",k.any);b.opt("rewrite_original",!0);(g=!k.any||b.harmony(d.harmony.COMMERCIAL_LINK_EVENTS)||k.convert_minimum_bid)&&b.registerProcessor(d.bind(function(b){this.initDomainLookup();
this.saveDomain(b)},this),{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,d.on("DOMReady",d.bind(this.getDomains,this)))}}(),onDomainApi:function(g){var k=b.opt("commercial")||{};d.each(g.results,function(b,a){k[a]=b.unlink?!1:!0});b.opt("commercial",k);b.registerProcessor(d.bind(function(b){m.minimumBidUnlink(b)},this),{any:!0})},saveDomain:function(b){b=d.canonicalizeHostname(b);q[b]=q[b]||1},minimumBidUnlink:function(g){var m=d.canonicalizeHostname(g);!1===(b.opt("commercial")||
{})[m]&&d.unlink(g)}};return{init:d.bind(m.init,m),initNodes:function(){g&&m.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(k,d,b){var q=[],g=b.platform();k={crawl:function(b){if(g&&!("array"!==d.type(b)||0===b.length))b=d.all(b,function(b){return!d.contains(q,b)}),b=this.findPostsById(b),d.each(b,d.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=d.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return d.all(d.map(g.getPosts(),function(b){return{el:b,id:g.getPostId(b)}}),
function(g){return d.contains(b,g.id)})},processPosts:function(m){m=d.map(m,function(b){q.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:d.toJSON({ct:m,pt:g.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return d.pii.redact(b)}};return{"public":{crawl:d.bind(k.crawl,k)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(k,d,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(k,d,b){k=d.extend({key:null},k);var q={init:function(b){d.each(this.getDRSearchForms(b),function(b){if(!d.cache(b,"evented")){var g=q.getInput(b),k=function(){g.value||d.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(b,"evented",!0);b.onsubmit=null;g.onfocus=null;g.onblur=null;d.on(g,"focus",function(){d.css(g,{"background-image":"none"})});d.on(g,"blur",k);k();d.on(b,"submit",function(d){q.onSubmit(d,b)})}})},
getDRSearchForms:function(b){var m=[];d.each(b,function(b){"element"===d.type(b)&&d.each(b.getElementsByTagName("form"),function(b){q.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&m.push(b)})});return m},getInput:function(b){return b.p||b.q2},onSubmit:function(g,m){g=g||window.event;var n="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:q.getInput(m).value}),n=d.createA(n,"_blank");d.cache(n,"params",{key:k.key});b.click(n);return d.preventDefault(g)}};if(k.key)return{init:d.bind(q.init,q),
initNodes:function(b){q.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(k,d,b){k=d.extend({level:d.harmony.DEFAULT},k);return{init:function(){var d=parseFloat(k.level,10);isFinite(d)&&b.opt("harmony_level",d)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(k,d,b,q){var g,m={uuid:"uuid",index:"idx",optimized_url:"url",aliases:"aka"};k=d.extend({scope:"body"},k);g={cache:function(){var b={},d={};return{links:{get:function(d){return b[d]},set:function(d,a){var c={};c[m.optimized_url]=a[m.optimized_url];c[m.uuid]=a[m.uuid];c[m.aliases]=a[m.aliases];b[d]=c}},stats:{increment:function(b,a){d[b]||(d[b]={});if(a)if("rep"===a)d[b].rep=(d[b].rep||0)+1;else{var c;c=d[b].ex=d[b].ex||{};c[a]=(c[a]||0)+1}else d[b].n=(d[b][m.insertion_count]||
0)+1},getAndReset:function(){var b=d;d={};return b}}}}(),filterLinkNodes:function(){var b={sameDomainOrInternal:function(){var b=window.location.hostname;return function(a){return b===a.hostname}}()},k=function(g){return d.all(g,function(a){return d.every(b,function(c){return!c(a)})})};return function(b){var a={needs_optimization:[],needs_call:[]};d.each(k(b),function(c){var b=g.cache.links.get(c.href);b&&b[m.uuid]&&d.cache(c,"uuid",b[m.uuid]);b&&b[m.optimized_url]?a.needs_optimization.push(c):b&&
"false"===b[m.optimized_url]||a.needs_call.push(c)});return a}}(),generateAliases:function(b){var k=g.cache.links.get(b.href),q=[],q=q.concat(k[m.aliases]||[]);q.push(d.canonicalizeHostname(b.href));q.push(d.canonicalizeHostname(k[m.optimized_url]));return d.unique(q)},getLinks:function(k){b.opt("time_api")&&q.event.start("opt");b.sendLinks("optimize",{ver:b.opt("links_version"),u:location.href,mode:["O"],links:d.unique(d.map(k,function(b){return b.href}))},{fn:d.bind(g.onOptimizeApi,g),ssl:b.opt("dev")?
!1:!0},k)},log:d.batchable(function(){var b={stats:d.toJSON(g.cache.stats.getAndReset())};4<b.stats.length&&q("loJsLog",b)},function(){return{timeout:1E3}}),onOptimizeApi:function(k){var p=k.response[0],B=k.args.links,a=k.data[0];b.opt("time_api")&&q.event.stop("opt");"object"===d.type(p)&&(k=["opt","non","unk"],d.each(k,function(a){p[a]&&p[a].length&&d.each(p[a],function(b){var d=B[b[m.index]];"non"===a&&(b[m.optimized_url]=!1);g.cache.links.set(d,b)})}),k=g.filterLinkNodes(a),g.optimizeLinks(k.needs_optimization))},
optimizeLinks:function(b){d.each(b,function(b){d.cache(b,"rewrit",!1)});b=g.runExclusionFilters(b);d.each(b,this.optimizeLink);d.traits.json&&g.log()},optimizeLink:function(){var b=function(a){return a.replace(/^https?:\/\//,"")},p=function(a,c){for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(document.createTextNode(c))},q=function(a){var c=a.href,e=a.textContent||a.innerText,f=Boolean(e),h=g.generateAliases(a),k=function(){var a=b(c).toLowerCase(),f=e.toLowerCase().replace(a,"");return d.some(h,
function(a){return-1!==f.indexOf(a.toLowerCase())})},l=function(){var a=e.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+d.map(a,d.escapeRegExp).join(".+")+"$").test(c)},m=function(){var c=d.canonicalizeHostname(a);return d.canonicalizeHostname(d.createEl("a",{href:e}))===c},r=function(){var c;return m()?(c=d.fromQuery(a.search),d.find(c,function(a){return a===e})):!1};return{full_replace:Boolean(f&&(c===e||b(c)===e||l()||r())),exclude:Boolean(f&&k()),partial_replace:Boolean(f&&(-1!==
e.indexOf(c)||-1!==e.indexOf(b(c))))}};return function(a){var c,e=g.cache.links.get(a.href),f=e[m.optimized_url];c=q(a);if(f&&!k.observer){if(c.full_replace)p(a,f),g.cache.stats.increment(e[m.uuid],"rep");else{if(c.exclude){g.cache.stats.increment(e[m.uuid],"a");return}c.partial_replace&&(c="undefined"!==d.type(a.textContent)?a.textContent:a.innerText,c=-1!==c.indexOf(a.href)?c.replace(a.href,f):c.replace(b(a.href),f),p(a,c),g.cache.stats.increment(e[m.uuid],"rep"))}f=-1===f.indexOf("http://")?"http://"+
f:f;a.href=f}g.cache.stats.increment(e[m.uuid]);d.cache(a,"rewrit",!0)}}(),runExclusionFilters:function(){var b=d.generateNodeFilter({classes:["nooptimize","norewrite"],rels:["nooptimize","norewrite","noskim"],custom:function(a,c){if(c)return Boolean(d.cache(a,"type"))}}),k=function(a){var c=g.generateAliases(a),b=d.context(a).document.title;return d.every(c,function(a){return-1===b.indexOf(a)})},q=function(){var a=function(a,c){var b=d.reduce([],["prev_tokens","next_tokens"],function(c,b){a[b]&&
a[b].length&&(c=c.concat(a[b]));return c}).join(" ").toLowerCase();return d.some(c,function(a){return-1!==b.indexOf(a.toLowerCase())})},c=function(){var a=function(a){a="undefined"!==d.type(a.textContent)?a.textContent:a.innerText;return d.all(a.split(/\s+/g),function(a){return""!==a})};return function(c){for(var b={prev_tokens:[],next_tokens:[]};c&&c!==document.body.parentNode;){for(var g=b,l=c.previousSibling,k=c.nextSibling;l||k;)l&&(d.nodesOfType([l],1,3).length&&"SCRIPT"!==l.tagName)&&(g.prev_tokens=
g.prev_tokens.concat(a(l).reverse())),l=!l?!1:l.previousSibling,k&&(d.nodesOfType([k],1,3).length&&"SCRIPT"!==k.tagName)&&(g.next_tokens=g.next_tokens.concat(a(k))),k=!k?!1:k.nextSibling;if(20<b.prev_tokens.length+b.next_tokens.length+0)break;c=c.parentNode}return b}}();return function(b){var d=g.generateAliases(b);b=c(b);80<b.prev_tokens.length+b.next_tokens.length+0&&(b.prev_tokens=b.prev_tokens.slice(0,40),b.next_tokens=b.next_tokens.slice(0,40));b.prev_tokens=b.prev_tokens.reverse();return!a(b,
d)}}();return function(a){return d.all(a,function(a){var d=g.cache.links.get(a.href)[m.uuid];if(b(a))if(q(a)){if(!k(a))return g.cache.stats.increment(d,"t"),!1}else return g.cache.stats.increment(d,"p"),!1;else return g.cache.stats.increment(d,"n"),!1;return!0})}}()};return{initNodes:function(b){var m;b=d.nodesOfType(b,1);b=d.links(b,k.scope);b=g.filterLinkNodes(b);(m=b.needs_optimization)&&m.length&&g.optimizeLinks(m);(b=b.needs_call)&&b.length&&g.getLinks(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(k,d,b,q){var g,m,n,p,B=null,a=null;k=d.extend({cat:null,dynamic_sample_rate:1,key:null,link_phrases:!0,link_target:null,link_urls:!0,manual_mode:1===k.mode,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},k);if(k.key)return g=b.platform(),m={cache:function(){var a={},b={},f=function(f,g){var h={};d.isArray(g)&&0<g.length&&d.find(g,function(a){var c=b;if(c[a]){if(f)return h[f]=c[a][f],!0;d.each(c[a],function(a,c){h[c]||(h[c]=a)})}});
h=d.extend(d.clone(a),h);return f?h[f]:h},g=function(f,g,h){(h=d.isArray(h)&&0<h.length?h:null)&&d.each(h,function(a){var c=b;c[a]=c[a]||{};"L"!==g.type&&(c[a][f]||(c[a][f]=g))});if(!h||"L"===g.type)a[f]||(a[f]=g);return!0},m=function(a,c,b){var e=d.all(d.toArray(arguments),function(a){return Boolean(a)});"array"===d.type(e[e.length-1])&&(b=e.pop());a=e[0];c=e[1];if(1>=e.length)return f(a,b);if(2===e.length)return g(a,c,b)};k.manual_mode&&d.extend(m,{reset:function(){a={};b={}}});return m}(),focusLink:function(a){a.id||
(a.id=d.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,d,f=b.opt("partner"),g={};for(a in f)break;if(a)for(d in f[a])g[a+"_"+d]=f[a][d];return g},getPhrases:function(a,e){b.opt("time_api")&&q.event.start("ins");b.api("insert",d.extend(m.getPartnerParams(),{cat:k.cat,i:e?e.join("|"):null,mode:k.mode,pt:g.id,ps:k.product_source,u:location.href}),{fn:d.apiCallback(m.onInsertApi,m)},a,e)},hasCalled:function(){var a={},b=Math.random()<k.dynamic_sample_rate,
f=function(a){return b&&d.isArray(a)?d.map(a,function(a){return f(a)}):b&&a===d.platforms.DEFAULT_POST_ID?location.href:a},g=function(b){b=f(b);return d.isArray(b)&&b.length?Boolean(d.all(b,function(b){return a[b]}).length===b.length):Boolean(a[d.platforms.DEFAULT_POST_ID])},m=function(b){b=f(b);d.isArray(b)&&b.length?d.each(b,function(b){a[b]=!0}):a[d.platforms.DEFAULT_POST_ID]=!0};return function(a,b){return b?m(a):g(a)}}(),init:function(){k.scope=k.scope||g.scope;k.link_urls&&(p=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"))},initLink:function(a,e,f){var g=k.link_target;if(g="U"===e.type?b.opt("link_target"):g||f)a.target=g;a.href||(a.href=e.url);a.rel="nofollow";d.cache(a,"params",{exp:B,key:k.key,mid:e.mid,type:e.type||null});d.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var a,b=d.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return d.matches(a,
"a")&&Boolean(a.href)}}),f=function(a,c,d,k){if(b(c,{ancestors:!Boolean(k),self:!0}))if(3===c.nodeType)g(a,c,d);else if(1===c.nodeType)for(c=c.firstChild;c;)k=c.nextSibling,f(a,c,d,!0),c=k},g=function(a,b,c){var d=!1,e=b.parentNode,f=function(a,b){e.insertBefore(a,b);e.removeChild(b)};e&&(b.data&&(d=a.test(b.data.replace(/\s+/," "))),d&&n(a,b,c,f))},n=function(b,e,f,g){for(var h,n,q,p,w=function(b){var e;b=!b||!k.per_phrase||!a[b.phrase]||a[b.phrase].count<k.per_phrase;e=!k.per_page||d.reduce(0,a,
function(a,b){return a+b.count})<k.per_page;return b&&e},B=function(a,b,c){var e,f,g;if(!c.phrase)return!0;f=d.createEl("span");b.parentNode.insertBefore(f,b);f.appendChild(b);g=d.geometry(f);(k.proximity||k.same_proximity)&&d.find(m.cache(a),function(a){var b,f;if(a.links){if((b=m.normalizePhrase(a.phrase)===m.normalizePhrase(c.phrase))&&!k.same_proximity||!b&&!k.proximity)return!1;f=b?Math.max(k.same_proximity,k.proximity):k.proximity;a.links=d.all(a.links,function(a){var b=d.isInDom(a.el);!e&&
b&&(e=d.find(a.segments,function(a){a=a.geometry;a=d.extend({},a);a.x1-=f;a.y1-=f;a.x2+=f;a.y2+=f;if(a.x1<g.x2&&a.x2>g.x1&&a.y1<g.y2&&a.y2>g.y1)return!0}));return b});return e}});return function(a){f.parentNode.insertBefore(b,f);f.parentNode.removeChild(f);return a}(!e)},U=function(a,b){var c,e,f,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(e=k.length;c<e;c++)f=k[c],void 0===g||f.offsetTop===g.offsetTop?l.els.push(f):(h.segments.push(l),l={els:[f]}),g=f;l.geometry=d.geometry.apply(d,
l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};e&&e.data&&""!==e.data&&(Boolean(!d.traits.fastRegexp&&(q=e.data.match(/^\s+/)))||Boolean(q=e.data.match(b)));)n=q[0],p=q.slice(1).join(""),h=(h=m.normalizePhrase(p))?m.cache(h,f):null,n=q.index+n.length-p.length,0<n&&(e=e.splitText(n)),n=e.length<=p.length?null:e.splitText(p.length),p&&!h&&(h={url:p.match(/^https?:\/\//i)?p:"http://"+p,type:"U"}),h&&(h.url.match(/https?:\/\//i)&&p&&w(h)&&B(f,e,h))&&(p=l(p,h),d.cache(p,"unlinked")||
(g(p,e),U(p,h),e=h.phrase||h.url,a[e]=a[e]||{count:0,phrase:h.phrase,type:h.type},a[e].count++)),e=n},l=function(a,b){var c;c=d.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";d.cache(c,"type","inserted");d.cache(c,"phrase",a);k.ui&&"U"!==b.type&&(c.title="Link added by VigLink");m.initLink(c,b);return c};return function(g,h){var l=m.regexp(h);a={};l&&(d.each(d.all(g,b),function(a){f(l,a,h)}),k.link_phrases&&m.log(a))}}(),insertManually:function(){var a=
!1,b=d.clone(k),f=function(a){return d.map(a,function(a,b){return{phrase:b,type:"M",url:a}})};return function(g,p,l){var q,r=!1;n.init();k.manual_mode&&!a&&(a=!0,q=p=p||{},k.same_proximity=q.same_proximity||k.same_proximity,k.proximity=q.proximity||k.proximity,k.per_page=q.per_page||k.per_page,k.per_phrase=q.per_phrase||k.per_phrase,q=p.target_node||document.body,g=f(g),m.loadPhrases(g,[q]),k=b,m.cache.reset(),r=!0,a=!1);"function"===d.type(l)&&l(r,q)}}(),loadPhrases:function(a,b,f){d.each(a,function(a){a.phrase&&
a.url&&(a.phrase=m.normalizePhrase(a.phrase),m.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},f))});m.hasCalled(f,!0);this.insertLinks(b,f)},log:function(b){var e=0,f=0,g=[];d.each(b,function(a,b){var c=parseInt(a.count,10);0<c&&("U"===a.type?f+=c:"M"!==a.type&&g.push({phrase:b,type:a.type,count:c}),e+=c)});0<e&&q("insert",[{ct:e,cl:f,exp:B,imp_id:a,phrases:d.toJSON(g)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},
onInsertApi:function(c,e,f){b.opt("time_api")&&q.event.stop("ins");"object"===d.type(c)&&(B=c.exp,a=c.imp_id,c.results&&this.loadPhrases(c.results,e,f))},regexp:function(a){var b;a=m.cache(a);a=d.map(a,function(a,b){return d.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(p?"(?:"+b+"|"+p.source+")":b,"i"));return b||p}},n={init:d.destructing(d.bind(m.init,m)),initNodes:function(a){var b;k.scope&&(a=d.unique(d.reduce([],d.withScope(a,
k.scope),function(a,b){return a.concat(b[1])})));a.length&&(b=g.getPostIds(a),k.link_phrases&&!m.hasCalled(b)?m.getPhrases(a,b):m.insertLinks(a,b))}},k.manual_mode&&d.extend(n,{"public":{run:m.insertManually}}),n};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(k,d,b){var q;k=d.extend({log_links:!0,log_status:!1,pai_type:[],scope:"body"},k);q={logLinks:function(g){b.sendLinks("optimize",{ver:b.opt("links_version"),u:location.href,mode:["P"],links:d.unique(d.map(g,function(b){return b.href}))},{ssl:b.opt("dev")?!1:!0,jsonp:!1})},logStatus:function(g){d.createEl("img").src=d.updateUrl(b.opt("api_url"),{pathname:"/api/sync/status.gif",search:"?"+d.toQuery({st:g})})},run:function(){var b=k.pai_type;d.isArray(b)&&b.length&&
q.sync(b)},sync:function(){return function(g){var m,n;m=g.pop();n=d.updateUrl(b.opt("api_url"),{pathname:"/api/sync.gif",search:"?"+d.toQuery({partner_id:m})});m=d.createEl("img");d.on(m,"load",function(){k.log_status&&q.logStatus("su");g.length&&q.sync(g)});d.on(m,"error",function(){k.log_status&&q.logStatus("fa");g.length&&q.sync(g)});k.log_status&&q.logStatus("bg");m.src=n}}()};return{init:function(){q.run()},initNodes:function(b){(b=d.links(b,k.scope))&&(b.length&&k.log_links)&&q.logLinks(b)}}};
