ALTER TABLE SIP_SM.TB_SERVICES MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER TABLE SIP_SM.TB_WTMPS_ARCHIVE MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER TABLE SIP_SM.TB_WTMPS_SESSIONS_ARCHIVE MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER TABLE SIP_SM.TB_WTMPS_SESSION_CHARGES MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER TABLE SIP_SM.TB_INVOICES MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER USER SIP_SM DEFAULT TABLESPACE USERS2;


ALTER INDEX SIP_SM.MOVE_USER_TWH MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.SRV_AB_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.SRV_CNT_ID_IX MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.SRV_PK MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.SRV_US_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWH_DATE_IX_LOC MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSA_PK MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWH_STATUS_TYPE MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSA_IP_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWH_LOGIN_IX MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSC_CHG MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSC_PK MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSC_TWSA_IX MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.TWSC_US_USER_NAME_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
ALTER INDEX SIP_SM.WTMPS_ARCH_I$ MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;


--ALTER INDEX SIP_SM.INV_AB_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
--ALTER INDEX SIP_SM.INV_IST_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
--ALTER INDEX SIP_SM.INV_ITP_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
--ALTER INDEX SIP_SM.INV_PK MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
--ALTER INDEX SIP_SM.INV_SRD_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;
--ALTER INDEX SIP_SM.INV_US_FK_I MODIFY DEFAULT ATTRIBUTES   TABLESPACE USERS2;













