set pagesize 10000;
set linesize 1500;
SELECT 'ALTER TABLE '|| TABLE_OWNER||'.'||TABLE_NAME||' MOVE PARTITION ' ||  PARTITION_NAME||  ' TABLESPACE USERS2 PARALLEL(DEGREE 8) NOLOGGING;'  FROM ALL_tab_partitions 
WHERE TABLE_OWNER = 'SIP_SM' 
AND table_NAME NOT LIKE 'BIN$%'
ORDER BY TABLE_NAME,PARTITION_NAME;