SELECT DBMS_METADATA.get_ddl ('USER', 'SIP_W') FROM DUAL;
--SELECT DBMS_METADATA.get_ddl ('USER', 'RADIUS_WIFI') FROM DUAL;
--SELECT DBMS_METADATA.get_ddl ('USER', 'RADIUS') FROM DUAL;
--SELECT DBMS_METADATA.get_ddl ('USER', 'SIP_WWW') FROM DUAL;

--alter user sip_w IDENTIFIED BY VALUES '073DA8EE5C648E40';
--alter user sip_w IDENTIFIED BY dPaGX2fe;

--alter USER "RADIUS_WIFI" IDENTIFIED BY VALUES '84455D0D20B51B0F';
--alter USER "RADIUS" IDENTIFIED BY VALUES 'AA890F00E9A5F6B3';    
--alter USER "SIP_WWW" IDENTIFIED BY VALUES '0C313BFE1908D1BE';