SELECT LOCAL_TRAN_ID, GLOBAL_TRAN_ID, STATE, MIXED, HOST, COMMIT#   FROM DBA_2PC_PENDING;


--EXECUTE DBMS_TRANSACTION.PURGE_LOST_DB_ENTRY('273.53.62985');
--commit;
  
SELECT 'commit force '''||LOCAL_TRAN_ID||''';' FROM DBA_2PC_PENDING;

select 'EXECUTE DBMS_TRANSACTION.PURGE_LOST_DB_ENTRY('''||LOCAL_TRAN_ID||''');'FROM DBA_2PC_PENDING;

SELECT 'commit force '''||LOCAL_TRAN_ID||''';' FROM DBA_2PC_PENDING;

select 'DBMS_TRANSACTION.PURGE_LOST_DB_ENTRY('''||LOCAL_TRAN_ID||''');commit;'FROM DBA_2PC_PENDING;
