GRANT WM_ADMIN_ROLE TO SIP_W;
GRANT MGMT_USER TO SIP_W;
GRANT MDSS_ROLE TO SIP_W;
GRANT CONNECT TO SIP_W;
GRANT RESOURCE TO SIP_W;
GRANT XDBADMIN TO SIP_W;
GRANT SELECT_CATALOG_ROLE TO SIP_W;
GRANT EXECUTE_CATALOG_ROLE TO SIP_W;
GRANT CREATE TABLE TO SIP_W;
GRANT CREATE SESSION TO SIP_W;
GRANT EXPORT FULL DATABASE TO SIP_W;
GRANT UNLIMITED TABLESPACE TO SIP_W;
GRANT CREATE ANY TABLE TO SIP_W;
ALTER USER SIP_W DEFAULT ROLE ALL;
grant read, write on directory export to SIP_W;
 --Grant the privilege EXEMPT ACCESS POLICY to the exporting user
grant EXEMPT ACCESS POLICY to System;
grant EXEMPT ACCESS POLICY to SIP_W;


GRANT WM_ADMIN_ROLE TO SIP_W;
GRANT MGMT_USER TO SIP_W;
GRANT MDSS_ROLE TO SIP_W;
GRANT CONNECT TO SIP_W;
GRANT RESOURCE TO SIP_W;
GRANT XDBADMIN TO SIP_W;
GRANT SELECT_CATALOG_ROLE TO SIP_W;
GRANT EXECUTE_CATALOG_ROLE TO SIP_W;
GRANT CREATE TABLE TO SIP_W;
GRANT CREATE SESSION TO SIP_W;
GRANT EXPORT FULL DATABASE TO SIP_W;
GRANT UNLIMITED TABLESPACE TO SIP_W;
GRANT CREATE ANY TABLE TO SIP_W;
ALTER USER SIP_W DEFAULT ROLE ALL;

 grant IMP_FULL_DATABASE to SIP_W;
 grant EXP_FULL_DATABASE to SIP_W;
 grant EXEMPT ACCESS POLICY to System;
grant EXEMPT ACCESS POLICY to SIP_W;

  GRANT DATAPUMP_EXP_FULL_DATABASE TO SIP_W;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO SIP_W;
   GRANT EXPORT FULL DATABASE TO SIP_W;
  GRANT SELECT ANY DICTIONARY TO SIP_W;
  GRANT UNLIMITED TABLESPACE TO SIP_W;
  
  
  GRANT WM_ADMIN_ROLE TO SIP_W;
GRANT MGMT_USER TO SIP_W;
GRANT MDSS_ROLE TO SIP_W;
GRANT CONNECT TO SIP_W;
GRANT RESOURCE TO SIP_W;
GRANT XDBADMIN TO SIP_W;
GRANT SELECT_CATALOG_ROLE TO SIP_W;
GRANT EXECUTE_CATALOG_ROLE TO SIP_W;
GRANT CREATE TABLE TO SIP_W;
GRANT CREATE SESSION TO SIP_W;
GRANT EXPORT FULL DATABASE TO SIP_W;
GRANT UNLIMITED TABLESPACE TO SIP_W;
GRANT CREATE ANY TABLE TO SIP_W;
ALTER USER SIP_W DEFAULT ROLE ALL;
grant read, write on directory export to SIP_W;