CREATE USER SIP_SR_NEW
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 11 Roles for SIP_SR_NEW 
  GRANT CONNECT TO SIP_SR_NEW;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO SIP_SR_NEW;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO SIP_SR_NEW;
  GRANT DBA TO SIP_SR_NEW;
  GRANT EXECUTE_CATALOG_ROLE TO SIP_SR_NEW;
  GRANT EXP_FULL_DATABASE TO SIP_SR_NEW;
  GRANT IMP_FULL_DATABASE TO SIP_SR_NEW;
  GRANT RESOURCE TO SIP_SR_NEW;
  GRANT SELECT_CATALOG_ROLE TO SIP_SR_NEW;
  GRANT WM_ADMIN_ROLE TO SIP_SR_NEW;
  GRANT XDBADMIN TO SIP_SR_NEW;
  ALTER USER SIP_SR_NEW DEFAULT ROLE ALL;
  -- 6 System Privileges for SIP_SR_NEW 
  GRANT CREATE ANY TABLE TO SIP_SR_NEW;
  GRANT CREATE SESSION TO SIP_SR_NEW;
  GRANT CREATE TABLE TO SIP_SR_NEW;
  GRANT EXEMPT ACCESS POLICY TO SIP_SR_NEW;
  GRANT EXPORT FULL DATABASE TO SIP_SR_NEW;
  GRANT UNLIMITED TABLESPACE TO SIP_SR_NEW;
  -- 1 Object Privilege for SIP_SR_NEW 
    GRANT READ, WRITE ON DIRECTORY EXPORT TO SIP_SR_NEW;
    
grant read, write on directory export to SIP_SR_NEW;
  grant IMP_FULL_DATABASE to SIP_SR_NEW;
 grant EXP_FULL_DATABASE to SIP_SR_NEW;
 grant EXEMPT ACCESS POLICY to System;
grant EXEMPT ACCESS POLICY to SIP_SR_NEW;
  GRANT DATAPUMP_EXP_FULL_DATABASE TO SIP_SR_NEW;
  GRANT DATAPUMP_IMP_FULL_DATABASE TO SIP_SR_NEW;
  
   
  GRANT WM_ADMIN_ROLE TO SIP_SR_NEW;
GRANT MGMT_USER TO SIP_SR_NEW;
GRANT MDSS_ROLE TO SIP_SR_NEW;
GRANT CONNECT TO SIP_SR_NEW;
GRANT RESOURCE TO SIP_SR_NEW;
GRANT XDBADMIN TO SIP_SR_NEW;
GRANT SELECT_CATALOG_ROLE TO SIP_SR_NEW;
GRANT EXECUTE_CATALOG_ROLE TO SIP_SR_NEW;
GRANT CREATE TABLE TO SIP_SR_NEW;
GRANT CREATE SESSION TO SIP_SR_NEW;
GRANT EXPORT FULL DATABASE TO SIP_SR_NEW;
GRANT UNLIMITED TABLESPACE TO SIP_SR_NEW;
GRANT CREATE ANY TABLE TO SIP_SR_NEW;
ALTER USER SIP_SR_NEW DEFAULT ROLE ALL;