DROP VIEW SYS.SIP_SR_NEW_PART_VIEW;

/* Formatted on 10.06.2016 10:21:41 (QP5 v5.252.13127.32867) */
CREATE OR REPLACE FORCE VIEW SYS.SIP_SR_NEW_PART_VIEW
(
   TABLE_NAME,
   PARTITION_NAME,
   NUM_ROWS
)
AS
   SELECT table_name, partition_name, num_rows
     FROM dba_tab_partitions
    WHERE table_owner = 'SIP_SR_NEW';


CREATE OR REPLACE SYNONYM SIP_SR_NEW.PART_VIEW FOR SYS.SIP_SR_NEW_PART_VIEW;
