select owner,table_name,num_rows from dba_tables where PARTITIONED='YES' and OWNER in ('SIP_W', 'SIP_IBS', 'SIP_WWW')
and table_name not in ('ABONENT_JN','CT_POOLS_JN','VOIP_LOG_DETAIL','JR_IP','TB_BLOCKING_ARCHIVE','TB_INVOICES','TB_OPTION_STATUS','TB_USER_SERV_ATTRS_JN','TB_OPTION_STATUS_JN','TB_SERVICES_JN',
'TB_LDAP_TASKS_REDEF','TB_LDAP_TASKS','ONF_REGS','TB_ACCOUNTS_JN','TB_SERVICES','TB_WTMPS_ARCHIVE')

--ne nado JR_IP

